server:
  port: 8085
  error:
    include-stacktrace: on_param

spring:
  application:
    name: train-up
  flyway:
    baseline-on-migrate: true
    url: ${DATABASE_URL:}
    user: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
  datasource:
    url: ${DATABASE_URL:}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    sql: debug
    br.com.customer: DEBUG

jwt:
  public-key: classpath:app.pub
  private-key: classpath:app.key